- website/docs/06-tutorials/how-to-use-azure-vm.md
- website/docs/06-tutorials/index.md
Adds Azure-importer quick start guide
> Add azure quick start

- docs/01-overview.md
adds disclaimer to overview page in docs
> add disclaimer to overview page

- docs/05-models.md
- docs/06-specification/computation-pipeline.md
Adds information and links explaining time synchronization to website
Closes https://github.com/Green-Software-Foundation/if/issues/364
> Add time sync docs

- docs/06-specification/index.md
> fix link to model-config -page

- docs/major-concepts/design-philosophy.md
- docs/major-concepts/index.md
Adds a page describing the overall Impact Framework design philosophy in the `Major Concepts` section
> Design philosophy page

- docs/developers/how-to-test-if.md
adds page on how to write unit tests
> Unit-tests-page

- docs/contributions.md
Adds some advice to the contribution guide about finding good issues to work on.
> Add pr advice to contributions guide

- docs/reference/cli.md
adds `override-params` command to CLI reference docs
> add reference doc about overriding params

- docs/major-concepts/if.md
- docs/major-concepts/manifest-file.md
- docs/users/quick-start.md
Adds information about output config to several pages
> Add info on output config

- docs/major-concepts/groupby.md
- docs/major-concepts/index.md
adds new page describing groupby plugin
> add docs page on groupby

- docs/major-concepts/aggregation.md
- docs/major-concepts/if.md
- docs/major-concepts/index.md
- docs/major-concepts/plugins.md
Adds new page describing aggregation feature.
> Add docs page on aggregation

- docs/major-concepts/manifest-file.md
If I got the code right this should be the correct description of such a nested example.
> fix: description of nested tree

- docs/major-concepts/if.md
Some minor specification improvements.
> fix: ie cli description

- docs/FAQ.md
> add FAQ page

- docs/major-concepts/index.md
- docs/major-concepts/parameters.md
adds new page detailing the parameter logic used in IF
> add page on parameter logic

- docs/reference/cli.md
- docs/users/how-to-export-to-csv.md
- docs/users/index.md
adds user doc on csv export and adds info to cli page
> add page on csv export

- src/pages/index.tsx
Removed training from the website
> Removed the hackathon training

- src/components/Hackathon/index.tsx
removes invitations to workshop from docs homepage
> rm workshop ionvite links

- docs/developers/how-to-visualize-results.md
the html plugin is not currently working - this PR removes instructions from the visualization page
> rm html plugin from viz page

- docs/intro.md
removes hackathon banner from if docs website Introduction page
> remove hackathon banner

- docs/reference/cli.md
- docs/users/how-to-compare-files-with-if-diff.md
Adds documentation to the CLI reference page about `if-diff` tool
Addresses https://github.com/Green-Software-Foundation/if/issues/707
> add docs for if-diff

- docs/users/how-to-write-manifests.md
> feat(docs): Added section with more details on how to integrate real-life data

- docs/major-concepts/pipelines.md
> fix links in pipeline landing page

- docs/developers/index.md
- docs/intro.md
- docs/major-concepts/index.md
- docs/reference/index.md
- docs/users/how-to-import-plugins.md
I tried to fix some broken link locations. Maybe this is helpful.
> Fixed links

- docs/major-concepts/plugins.md
- docs/reference/plugins.md
adds links to plugin submission page
> Add plugin submission details to if docs

- docs/major-concepts/index.md
- docs/reference/cli.md
adds info on debug flag to cli page
> Add debug info to docs

- docs/developers/how-to-refine-plugins.md
- docs/intro.md
- docs/major-concepts/plugins.md
- docs/reference/errors.md
- docs/users/how-to-compare-files-with-if-diff.md
- docs/users/how-to-export-to-csv.md
clarifies what plugins are and removes some references to if-plugins
> remove some references to if-plugins and clarify plugin definitions

- docs/reference/plugins.md
Adds link to copy-param to list of builtins
> Adds copy-param to list of builtins

- docs/reference/cli.md
- docs/users/how-to-verify-files-with-if-check.md
- docs/users/index.md
adds cli reference info and user tutorial to if-docs
> add info about if-check to if-docs

- docs/users/how-to-export-csv-file-with-if-csv.md
changes ## -> # to fix title error
> fix header level in csv page

- docs/reference/features.md
- docs/reference/index.md
- docs/users/how-to-use-the-explain-feature.md
- docs/users/index.md
adds docs on explainer feature
also adds a referenc epoage for IF features
> Explain-feature

- docs/pipelines/cpu-to-carbon.md
- docs/pipelines/instance-metadata.md
- docs/pipelines/sci.md
make csv-lookup pipeline confotm to template
> update csv-lookup pipeline to conform to template

- docs/users/quick-start.md
removes external plugin install step from quick start
> fix quick start

- docs/major-concepts/if.md
- docs/reference/cli.md
- src/pages/community.md
> add docs for append feature

- src/pages/index.tsx
> update watchers button link

- docs/reference/cli.md
- docs/users/how-to-build-container-images.md
- docs/users/how-to-deploy-to-kubernetes.md
- docs/users/how-to-use-containers.md
- docs/users/index.md
Added a reference for the `if-api` command for Web API created based on Discussion Green-Software-Foundation/if#1129.
> add if-api reference

- docs/FAQ.md
- docs/developers/how-to-build-plugins.md
- docs/developers/how-to-create-exhaust-script.md
- docs/developers/how-to-refine-plugins.md
- docs/developers/how-to-submit-plugins.md
- docs/developers/how-to-write-unit-tests.md
- docs/developers/index.md
- docs/major-concepts/aggregation.md
- docs/major-concepts/if.md
- docs/major-concepts/imp-file.md
- docs/major-concepts/plugins.md
- docs/major-concepts/regroup.md
- docs/major-concepts/time.md
- docs/pipelines/index.md
- docs/pipelines/instance-metadata.md
- docs/pipelines/sci.md
- docs/pipelines/teads.md
- docs/reference/cli.md
- docs/reference/errors.md
- docs/reference/features.md
- docs/reference/index.md
- docs/reference/plugins.md
- docs/users/how-to-verify-files-with-if-check.md
Fix some sidebars that were out of order.
Also add missing links to the index page.
> fix sidebar positions
